//===- ConstantFolding.cpp - Joy Constant Folding Pass --------------------===//
//
// Joy Compiler - Constant folding optimization pass
//
// Tries to fold operations whose operands are all constants into a
// single constant result.  For Joy dialect ops this relies on the
// `fold()` method generated by ODS (if any) and on the MLIR
// OperationFolder infrastructure.
//
// Even when no Joy op currently implements fold(), running the pass is
// safe — it simply finds nothing to fold — and it integrates cleanly
// into the OptimizationPipeline for future extensions.
//
//===----------------------------------------------------------------------===//

#include "mlir/IR/PatternMatch.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/FoldUtils.h"

using namespace mlir;

namespace {

struct ConstantFoldingPass
    : public PassWrapper<ConstantFoldingPass, OperationPass<>> {
  MLIR_DEFINE_EXPLICIT_INTERNAL_INLINE_TYPE_ID(ConstantFoldingPass)

  void runOnOperation() override {
    OperationFolder folder(&getContext());

    SmallVector<Operation *, 32> ops;
    getOperation()->walk([&](Operation *op) {
      if (op != getOperation() && !op->hasTrait<OpTrait::IsTerminator>())
        ops.push_back(op);
    });

    for (auto *op : ops)
      (void)folder.tryToFold(op);
  }

  StringRef getArgument() const override { return "joy-constant-folding"; }
  StringRef getDescription() const override {
    return "Perform constant folding on Joy dialect operations";
  }
};

} // namespace

void registerConstantFoldingPass() {
  PassRegistration<ConstantFoldingPass>();
}

std::unique_ptr<Pass> createConstantFoldingPass() {
  return std::make_unique<ConstantFoldingPass>();
}
