#!/usr/bin/env bash
# Regenerate joy/lib/backend/gpu/codegen_kernel.cu from the codegen stub
# MLIR files using joy-emit-cuda.  Invoked at build time by CMake's
# add_custom_command -- see joy/lib/backend/gpu/CMakeLists.txt.
#
# Usage:
#   regen_codegen_kernel.sh <joy-emit-cuda> <stub_f32.mlir> <stub_f16.mlir> <out.cu>
#
# Each stub is run through joy-emit-cuda with --run-pipeline so the
# emitter sees the post-codegen-rms-norm IR.

set -euo pipefail

if [ "$#" -ne 5 ]; then
    echo "usage: $0 <joy-opt> <joy-emit-cuda> <stub_f32.mlir> <stub_f16.mlir> <out.cu>" >&2
    exit 2
fi

OPT_BIN="$1"
EMIT_BIN="$2"
STUB_F32="$3"
STUB_F16="$4"
OUT="$5"
TMP="${OUT}.tmp"

for bin in "${OPT_BIN}" "${EMIT_BIN}"; do
    if [ ! -x "${bin}" ]; then
        echo "regen_codegen_kernel.sh: ${bin} is not executable" >&2
        exit 1
    fi
done

mkdir -p "$(dirname "${OUT}")"

# Banner
{
    echo "// Auto-generated by joy/scripts/regen_codegen_kernel.sh."
    echo "// DO NOT EDIT.  Regenerated each build from:"
    echo "//   ${STUB_F32}"
    echo "//   ${STUB_F16}"
    echo "// Pipeline:    joy-opt --codegen-rms-norm | joy-emit-cuda"
    echo "// Emitter:     joy::emitCudaC (lib/optimizer/EmitCudaC.cpp)"
    echo
} > "${TMP}"

# F32 pass: lower joyl -> codegen'd MLIR func -> CUDA C
"${OPT_BIN}" --codegen-rms-norm "${STUB_F32}" \
    | "${EMIT_BIN}" --source-tag="codegen_stub_f32.mlir" - >> "${TMP}"

# F16 pass: same, but strip the leading banner / #includes the second
# emitter run would re-emit.
"${OPT_BIN}" --codegen-rms-norm "${STUB_F16}" \
    | "${EMIT_BIN}" --source-tag="codegen_stub_f16.mlir" - \
    | awk '
        BEGIN { in_header = 1 }
        in_header && /^\/\// { next }
        in_header && /^#include/ { next }
        in_header && /^[[:space:]]*$/ { next }
        { in_header = 0; print }
    ' >> "${TMP}"

mv -f "${TMP}" "${OUT}"
echo "regen_codegen_kernel.sh: wrote ${OUT}"
